src/bin/build-keycloak-theme/build-keycloak-theme.ts, src/bin/build-keycloak-theme/generateKeycloakThemeResources.ts, src/test/bin/generateKeycloakThemeResources.ts
Right now upon generation of the `theme.properties` only `parent=keycloak` is added inside.
In our use case, we need to add some custom value pairs there (e.g. `env=dev`). Added some code to enable it.
Cheers!
=> Add possibility to add custom properties to theme.properties file

src/bin/build-keycloak-theme/build-keycloak-theme.ts, src/bin/build-keycloak-theme/generateDebugFiles/generateDebugFiles.ts, src/bin/build-keycloak-theme/generateJavaStackFiles.ts
Pom generated for scoped packages like `@scope/package` is malformed. Artifact id is generated using `package.json` name field, being an invalid pattern.
```
[ERROR] 'artifactId' with value '@scope/package' does not match a valid id pattern.
```
This PR sanitizes package name for using `scope-package` instead.
=> fix(mvn): scoped packages compatibility

src/lib/getKcContext/KcContextBase.ts
This PR adds the `name` field to the realm object in the KcContext Common type that is already being sent to the theme but wasn't declared, causing a compilation error when used.
I'm sending this PR directly because the fix seemed easy enough, but please let me know if there's something I misunderstood or missed
=> Adding name field to realm in KcContext type

src/lib/getKcContext/kcContextMocks/kcContextMocks.ts
PR https://github.com/InseeFrLab/keycloakify/pull/69 broke build because KcContext mock didn't create the realm name field. This PR fixes the issue.
Sorry about that 😰
=> Added realm name field to KcContext mocks object

src/bin/build-keycloak-theme/generateFtl/generateFtl.ts, src/lib/components/KcApp.tsx, src/lib/components/LoginIdpLinkEmail.tsx, src/lib/getKcContext/KcContextBase.ts, src/lib/getKcContext/kcContextMocks/kcContextMocks.ts
Adds `login-idp-link-email.ftl` page.
However, there is one issue. In the original template, the code looks like the following:
```
${msg("emailLinkIdp1", idpAlias, brokerContext.username, realm.displayName)}
```
Is it possible to somehow access the `brokerContext` inside kecloakify?
=> feat: add login-idp-link-email page

src/bin/build-keycloak-theme/replaceImportFromStatic.ts
Fixes https://github.com/InseeFrLab/keycloakify/issues/99
Following https://github.com/InseeFrLab/keycloakify/commit/0e194ee045f5710264a676e6dbcc4580a9ecccdb, the build time was greatly increased.
Allowing only letters (lowercase and uppercase without numbers and underscore) restores the performance of the build and still comply initial demand https://github.com/InseeFrLab/keycloakify/issues/90.
=> Issue #99 - Make replace less greedy in remplaceImportFromStatic

src/lib/useFormValidationSlice.tsx
Pass locale to getErrors for getting currect error messages on validation. Now, if you open register page on `https://datalab.sspcloud.fr/home` switch to franch, write `aa` on `Nom d'utilisateur`, press tab, you will see error on english.
=> pass locale to getGetErrors to get correct messages

src/bin/build-keycloak-theme/generateFtl/generateFtl.ts, src/lib/components/KcApp.tsx, src/lib/components/LoginConfigTotp.tsx, src/lib/getKcContext/KcContextBase.ts, src/lib/getKcContext/kcContextMocks/kcContextMocks.ts
Adds `login-config-totp.ftl` page, resolving #102
=> feat: add login-config-totp.ftl page

src/bin/build-keycloak-theme/generateFtl/generateFtl.ts, src/lib/components/KcApp.tsx, src/lib/components/LogoutConfirm.tsx, src/lib/getKcContext/KcContextBase.ts, src/lib/getKcContext/kcContextMocks/kcContextMocks.ts, src/lib/i18n/generated_kcMessages/18.0.1/login.ts, src/lib/i18n/index.tsx
Bonjour, pour Keycloak 18, je souhaiterai ajouter la possibilité de thémer 
[logout-confirm.tfl](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/logout-confirm.ftl)
La traduction française des nouveaux termes n'est pas encore dispo, y-a-t-il moyen de fournir une trad par défaut en FR pour les nouveaux termes (ex: `logoutConfirmTitle` ou `logoutConfirmHeader`), ou faut-il générer les fichiers pour la 
18.0.0 ?
=> feat: add logout-confirm

package.json, src/bin/create-keycloak-email-directory.ts, src/bin/download-builtin-keycloak-theme.ts, src/bin/generate-i18n-messages.ts, src/bin/keycloakify/BuildOptions.ts, src/bin/keycloakify/generateKeycloakThemeResources.ts, src/bin/keycloakify/keycloakify.ts, src/bin/tools/cliOptions.ts, src/bin/tools/downloadAndUnzip.ts, src/bin/tools/logger.ts, src/test/bin/generateKeycloakThemeResources.ts, src/test/bin/setupSampleReactProject.ts, yarn.lock
I have implemented a feature that adds support for the `--silent` flag that suppresses non-critical messages (i.e. warnings and errors are still surfaced)
I have decided to add two abstractions to implement this.
1. `getCliOptions` is a helper which is responsible for parsing different CLI options. Currently, it supports only the silent flag and the external assets flag. When we decide to add new flags, this abstraction might make it easier for us. It also brings a small utility library which takes care of parsing the CLI arguments and all the different edge cases of that.
2. `getLogger` is an abstraction for `console.*` functions that encapsulate some code (currently, only the silencing logic).  This allows us to replace `console.*` with `logger.*` in majority of the places and be done …
=> feat: add silent flag

developpement.md
I noticed this tiny typo when reading through the documentation. 
There also seems to be a typo in the file name `developpement.md`. Should it be `development.md`? I have kept the filename as it is, in case changing would break links.
=> Fix typo in development docs

package.json, src/bin/keycloakify/generateFtl/generateFtl.ts, src/lib/components/KcApp.tsx, src/lib/components/LoginUsername.tsx, src/lib/getKcContext/KcContextBase.ts, src/lib/getKcContext/kcContextMocks/kcContextMocks.ts, yarn.lock
Shown for the "Username Form" login step.
I would also like to work on:
- `login-password.ftl`
- `webauthn-authenticate.ftl`
But first want to see opinions on this!
p.s. I would appreciate a `hacktoberfest-accepted` label if you're okay with it!
=> Add `login-username` support

src/bin/keycloakify/generateStartKeycloakTestingContainer.ts
This minor change allows users to use the latest version of `bash` on Mac OS.
`/bin/bash` is very old on Mac OS, and many users will have `bash` from MacPorts or Homebrew. This change allows such users to be able to use the newer `bash` installation.
=> keycloak test script: use env to launch bash

src/bin/download-builtin-keycloak-theme.ts, src/bin/keycloakify/generateKeycloakThemeResources.ts, src/bin/keycloakify/keycloakify.ts, src/bin/link_in_test_app.ts, src/bin/tools/downloadAndUnzip.ts, src/bin/tools/grant-exec-perms.ts
Chown does not exist on widows. This PR uses nodejs's native fs.chmodSync instead
=> windows compatibility

src/bin/keycloakify/generateStartKeycloakTestingContainer.ts
The `generateStartKeycloakTestingContainer.ts` script is corrupt on windows because paths contain backslashes, I added code to replace all backslashes and additionally quoted the paths.
=> Fix start container script paths for windows

src/login/kcContext/KcContext.ts, src/login/kcContext/kcContextMocks.ts, src/login/pages/Login.tsx, src/login/pages/LoginUsername.tsx
Keycloak only treats `rememberMe` as true if the value is `"on"`. [ref](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authentication/authenticators/browser/AbstractUsernameFormAuthenticator.java#L210)
Additionally, it seems that keycloak will also return the attempted password on failed attempts, which could be useful to pre-populate the form on errors:
=> feat(login context): improve login typings

src/login/kcContext/KcContext.ts, src/login/kcContext/kcContextMocks.ts
This PR includes the credential reset url among the kcContext types.
Closes #278
=> Fix: add  to login reset password page

src/bin/keycloakify/generateFtl/generateFtl.ts, src/login/Fallback.tsx, src/login/kcContext/KcContext.ts, src/login/kcContext/kcContextMocks.ts, src/login/pages/SelectAuthenticator.tsx
Hey @garronej, thank you for creating and maintaining this great project. Keep up your amazing work for the open-source community.
This feature implements the `select-authenticator` page, which can be seen, when configuring a authentication flow with two authentication methods (for example OTP and WebAuthn).
I have tested the feature with Keycloak version 12.0.4 and 20.0.3. The following screenshot shows the page with the default Keycloak login style.
=> Add support for the select-authenticator.ftl page

keycloakify-json-schema.json, package.json, scripts/generate-json-schema.ts, src/bin/keycloakify/parsedPackageJson.ts, yarn.lock
Uses [zod-to-json-schema](https://www.npmjs.com/package/zod-to-json-schema) to add a script which generates a json schema for keycloakify apps to support intellisense. Ex:
```
// package.json
{
"$schema": "https://raw.githubusercontent.com/keycloakify/keycloakify/4a7dd64982711f388a25ffcb09c8ca8fa91d0f00/keycloakify-json-schema.json",
"name": "keycloakify-starter"
....
```
~If descriptions for fields are important, how do they get injected?~
Answered: Zod already has [describe](https://zod.dev/?id=describe) which `zod-to-json-schema` supports
=> feat: add keycloakify json schema

src/bin/tools/jar.ts
Many tools will handle zipfiles which lack directory entries just fine, others will not. Looks like the JDKs JAR libs are not handling  it well. This commit will make sure to create folder entries.
Should fix #330 and #331; Probably also #336, though I'd need some confirmation there since the reproduction path seems rather elaborate
=> fix: fix broken jar

src/bin/tools/trimIndent.ts
My node.js environment is v14.19.1. Because of that i get this error:
```
TypeError: strings[i].split(...).at is not a function
at populateTemplate (/path/foo/keycloakify-starter/node_modules/keycloakify/bin/tools/trimIndent.js:46:75)
```
=> Change node.js 16.6.0 dependency that Array.prototype.at

src/bin/keycloakify/replacers/replaceImportsFromStaticInJsCode.ts, test/bin/replaceImportFromStatic.spec.ts
- Handle both arrow functions and traditional function expressions
- Add tests to ensure correctness of transformations
- Remove redundant condition `${true ? "/build/" : ""}`
- Add `.replace(/\s+/g, " ").trim()` to make new code look like minified
=> fix: change JS path transformation for static resources

src/lib/pages/LoginConfigTotp.tsx
Apparently, the totp.policy.supportedApplications array returns the message keys for the apps, they need to be replaced by actual translation. To keep the default behavior before this PR, if the translation is not available, it will default to the message key on screen.
=> v6: Use message string for the supported applications

src/bin/keycloakify/generateFtl/pageId.ts, src/login/Fallback.tsx, src/login/TemplateProps.ts, src/login/kcContext/KcContext.ts, src/login/kcContext/kcContextMocks.ts, src/login/lib/useGetClassName.ts, src/login/pages/LoginDeviceVerifyUserCode.tsx, src/login/pages/LoginOauthGrant.tsx, stories/login/pages/LoginDeviceVerifyUserCode.stories.tsx, stories/login/pages/LoginOauthGrant.stories.tsx
Add login-oauth2-device-verify-user-code.ftl and login-oauth-grant.ftl to support oauth2 device flow
Note: 
- Need to have a client with device flow enabled in your Keycloak realm
- Locale change does not work but it is a keycloak bug (see issue here: https://github.com/keycloak/keycloak/issues/15717)
=> feat: add login-oauth2-device-verify-user-code and login-oauth-grant pages

src/bin/keycloakify/replacers/replaceImportsInCssCode.ts
The theme build process breaks CSS with properties that have multiple URL entries, like `background-image`:
```css
body {
background: image-set(url(/static/media/background@2x.94c864eb5ec048a3ccb1.jpg) 2x type("image/jpeg"), url(/static/media/background@2x.0ffa1919b145ac4f7e0d.webp) 2x type("image/webp"), url(/static/media/background.af4f4bf32ef997b6fd64.jpg) type("image/jpeg"), url(/static/media/background.d31202be8f25e0a757b2.webp) type("image/webp")) no-repeat 50%;
background-size: cover;
}
```
This is turned into:
```css
body {
background: image-set(var(--urlcf7fa946431c683);
background-size: cover;
}
```
and
```html
<style>
:root {
--urlcf7fa946431c683: url(${url.resourcesPath}/build/static/media/background@2x.94c864eb5ec048a3ccb1.jpg) 2x …
```
=> Handle CSS with multiple `url`s

src/login/Template.tsx
Since realm can't be changed without the page being refreshed I think this is a suitable solution.
The starter kit projects needs to adapt this change for people who is using that to benefit from this change.
=> Fixes #473: Set document title using the "loginTitle" translation

src/login/pages/LoginDeviceVerifyUserCode.tsx
align import statement with other page templates
=> refactor: point the import statement to keycloakify instead of internal

src/login/lib/useGetClassName.ts, src/login/pages/LoginOtp.tsx
Adds support for the case of more than 1 devices registered on the totp.
Previously the inputs were hidden, their name prop was incorrect and there was a bug in the interpolation of their value prop resulting in failure when submitting the form.
Javascript was pruned as it was found to be unnecessary under the new implementation
=> fix: radio inputs on login-otp page

src/account/Fallback.tsx, src/account/kcContext/KcContext.ts, src/account/kcContext/kcContextMocks.ts, src/account/pages/Applications.tsx, src/account/pages/FederatedIdentity.tsx, src/account/pages/Log.tsx, src/account/pages/Sessions.tsx, src/account/pages/Totp.tsx, src/bin/keycloakify/generateFtl/pageId.ts, stories/account/pages/Account.stories.tsx, stories/account/pages/Authenticator.stories.tsx, stories/account/pages/FederatedIdentity.stories.tsx, stories/account/pages/Log.stories.tsx, stories/account/pages/Pasword.stories.tsx, stories/account/pages/Sessions.stories.tsx, stories/account/pages/Totp.stories.tsx
Addition of the account page `FederatedIdentity`
Addition of stories for the account pages:
- Authenticator
- Log
Use of `Meta` from storybook instead of `ComponentMeta`
Correction of import path on `Log.tsx`
Correction on comma seperation on `realmRolesAvailable` on `Applications.tsx`
Correction of types on account `KcContext` and removal of `sessions` property on `Common` Type
=> Addition of Federated Identity Account page

src/account/pages/Applications.tsx, stories/account/pages/Applications.stories.tsx
- Added the applications.ftl story page.
- Fixed double comma that would appear if both `realmRolesAvailable` and `resourceRolesAvailable` attributes were present. Simply removed a check that was redundant (additional check added comma on line 69 in original file)
=> Added & Fixed Applications Page Under Account

src/login/pages/WebauthnRegister.tsx
I identified a bug where a comparison would always be false because arrays would be compared by reference.
I also changed the type-checking for an array to use the more semantic `Array.isArray` instead of comparing constructors.
=> Fix array comparison and improve type check

src/bin/start-keycloak/start-keycloak.ts
Hey there,
I noticed that the start-keycloak script refuses to run when the output of `docker --version` does not contain the word "Docker", which is the case when using Podman as a drop-in replacement for Docker.
~~This PR changes the script to only check if the command `docker --version` completes successfully instead of relying on a certain string in the output.~~
This PR changes the script to allow "podman" in the output of `docker --version` as well
=> Allow docker start script to work with podman

src/bin/keycloakify/generateFtl/ftl_object_to_js_code_declaring_an_object.ftl
=> fix: context filter smtp config syntax error

stories/login/pages/Register.stories.tsx
simply added in the missing parameter type that was throwing build errors on the register.stories.tsx file.
=> fix: added parameter type for story context on register page

stories/login/pages/Terms.stories.tsx
In addition to removing the error message on the terms and conditions page, I added a story for long terms and conditions. Since you brought this up, it reminded me that it was also a concern in my own personal project.
=> Removed Error Message from Terms and Conditions Page

src/bin/start-keycloak/start-keycloak.ts
Symlinking podman to docker generates this output and keycloakify looks for 'Docker' only
Tested locally, runs properly
=> Expanded podman support
