- .gitignore
- src/bin/build-keycloak-theme/generateFtl/common.ftl
- src/bin/build-keycloak-theme/generateFtl/generateFtl.ts
ref: https://github.com/InseeFrLab/keycloakify/issues/58
> fix: errors in common.ftl

- src/bin/build-keycloak-theme/generateFtl/generateFtl.ts
- src/lib/components/KcApp.tsx
- src/lib/components/LoginPageExpired.tsx
- src/lib/getKcContext/KcContextBase.ts
A minor addition with the "Page Expired" template, based on the original [login-page-expired.ftl](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/login-page-expired.ftl)
Great job btw!
> (feature) added login-page-expired.ftl

- src/bin/keycloakify/generateFtl/generateFtl.ts
- src/lib/components/KcApp.tsx
- src/lib/components/LoginPassword.tsx
- src/lib/getKcContext/KcContextBase.ts
- src/lib/getKcContext/kcContextMocks/kcContextMocks.ts
I'm going to start working on `webauthn-authenticate.ftl` now, I suspect it'll
be a little more difficult.
p.s. I would appreciate a `hacktoberfest-accepted` label if you're okay with it!
> Add support for `login-password.ftl`

- package.json
- src/bin/keycloakify/generateFtl/generateFtl.ts
- src/lib/components/KcApp.tsx
- src/lib/components/KcProps.ts
- src/lib/components/WebauthnAuthenticate.tsx
- src/lib/getKcContext/KcContextBase.ts
- src/lib/getKcContext/kcContextMocks/kcContextMocks.ts
- yarn.lock
Wow! This one sucks. Certainly more in need of review compared to
`login-username.ftl` and `login-password.ftl`...
> Add support for `webauthn-authenticate.ftl`

- src/bin/keycloakify/generateFtl/ftl_object_to_js_code_declaring_an_object.ftl
Addresses #217.
As mentioned in the replies, this is most likely a server-side issue that Keycloak should look into themselves.
However, as it poses a significant vulnerability, I've created a quick fix so that people using this library won't be affected by it.
Tested with a custom theme built using the lib, should also be tested using both starter projects.
> fix - handle username and password login errors the same way

- src/bin/keycloakify/index.ts
- src/bin/keycloakify/keycloakify.ts
- src/bin/tools/jar.ts
- src/bin/tools/zip.ts
So emberassing, introduced an 'improvement' to readability in last second. Unfortunately, nodejs streams are untyped. Will try and improve this further with typed streams in a follow-up PR
> Mvn begone addendum

- adding-text-keys.md
> fix(adding-text-keys): fix typo

- scripts/generate-i18n-messages.ts
- src/bin/tools/trimIndent.ts
- test/bin/tools/trimIndet.spec.ts
small addendums to previous merge:
1. use path.sep to be cross-platform instead of using OR on two different regex
2. improve typing on trimIndent
TODO
> Some-minor-fixes

- src/bin/tools/jar.ts
- src/bin/tools/walk.ts
- test/bin/jar.spec.ts
jar was not fixed after introduction of yazl; not  it should; added another proper test with actual files for good measure
> Fix-broken-jar

- src/bin/tools/downloadAndUnzip.ts
> feat: honor npmrc settings for ssl ca, cert and strict ssh handling

- src/login/kcContext/KcContext.ts
- src/login/pages/SamlPostForm.tsx
https://github.com/keycloakify/keycloakify/issues/341
> Fix saml post form

- src/bin/tools/crawl.ts
- test/bin/tools/crawl.spec.ts
> prevent crawlRec from crashing when dir_path does not exist

- src/login/kcContext/KcContext.ts
- src/login/kcContext/kcContextMocks.ts
- src/login/pages/Login.tsx
- stories/login/pages/Login.stories.tsx
- update KcContext definition for login.ftl
- update the username field rendering conditions in Login.tsx
Closes #397
> fix: usernameEditDisabled renamed to usernameHidden

- src/account/kcContext/kcContextMocks.ts
- src/login/kcContext/kcContextMocks.ts
- stories/account/pages/Pasword.stories.tsx
Closes https://github.com/keycloakify/keycloakify/issues/394
> feat: remove message from kcContextCommonMock

- src/bin/getSrcDirPath.ts
> Allow "keycloak_theme" as a theme source directory

- README.md
Just changed up the discord invitation link...
> Modified Readme.md to have a more visible discord invitation link

- src/login/UserProfileFormFields.tsx
Noticed this typo during migrating our Keycloakify Frontend ^^
Thanks for the great work!
> fix: Typo InputFiledByType to InputFieldByType

- stories/account/pages/Account.stories.tsx
- stories/account/pages/Applications.stories.tsx
- stories/account/pages/FederatedIdentity.stories.tsx
- stories/account/pages/Log.stories.tsx
- stories/account/pages/Password.stories.tsx
- stories/account/pages/Sessions.stories.tsx
- stories/account/pages/Totp.stories.tsx
- stories/login/pages/LoginIdpLinkConfirm.stories.tsx
- stories/login/pages/LoginIdpLinkEmail.stories.tsx
- stories/login/pages/LoginOauth2DeviceVerifyUserCode.stories.tsx
- stories/login/pages/LoginOauthGrant.stories.tsx
- stories/login/pages/LoginOtp.stories.tsx
- stories/login/pages/LoginPageExpired.stories.tsx
- stories/login/pages/LoginPassword.stories.tsx
- stories/login/pages/LoginRecoveryAuthnCodeConfig.stories.tsx
- stories/login/pages/LoginResetOtp.stories.tsx
- stories/login/pages/LoginResetPassword.stories.tsx
- stories/login/pages/LoginUpdatePassword.stories.tsx
- stories/login/pages/LoginUpdateProfile.stories.tsx
- stories/login/pages/LoginVerifyEmail.stories.tsx
- stories/login/pages/LoginX509Info.stories.tsx
- stories/login/pages/LogoutConfirm.stories.tsx
- stories/login/pages/SelectAuthenticator.stories.tsx
- stories/login/pages/UpdateEmail.stories.tsx
- stories/login/pages/WebauthnAuthenticate.stories.tsx
- stories/login/pages/WebauthnError.stories.tsx
- stories/login/pages/WebauthnRegister.stories.tsx
I've completed the login page stories. While I can't claim 100% coverage, I can confidently say that our coverage has improved significantly.
> Storybooks Second Release: Login Page Stories with Improved Coverage

- src/bin/tools/runFormat.ts
title: improve runFormat function to support versatile script names
description:
this enhancement allows the runFormat function to recognize and handle a broader range of script commands beyond just lint and format, adding versatility by allowing commands like lint:fix to be detected and executed. the filtering logic in scriptNames is updated to allow flexibility in defining multiple types of linting and formatting scripts.
motivation:
in many projects, lint and format commands are extended to handle additional tasks based on specific needs and workflows. examples of common script commands that go beyond simple lint and format include:
* lint:fix: used to apply automatic linting fixes separately when needed
* lint:staged: designed for git hooks, so only staged files are linted
* …
> fix(runFormat.ts): improve filtering in scriptNames

- src/login/KcContext/KcContext.ts
- src/login/lib/getUserProfileApi/getUserProfileApi.ts
Add maxLength passwordPolicy in the getUserProfileApi
> fix: add maxLength passwordPolicy in the getUserProfileApi
